### ISSUE TITLE
Описание предметной области/ТЗ

### ISSUE THREAD

**Issue by greguar97** [greguar97/greguar97#1]

**Comment by greguar97** [comment]
Первая версия тз:[ТЗ АНТОНОВ в1.docx](https://github.com/greguar97/greguar97/files/2636254/default.docx)

**Comment by wldmr-key** [comment]
ТЗ:
Область применения - это - кто применяет программу, а не для чего
Упрощение - это не функция. И улучшение это не функция.
DirectX 9 NVidia 8800GT или лучше - без этого не заработает?

Исследовательская часть:
Основная ошибка - предметная область представляет собой жизнь школы и родителей без всякого твоего приложения. Они без него века жили и еще столько же проживут. А, вот, тебе, для того чтобы написать вменяемое приложение нужно их жизнь исследовать и изложить результаты в описании предметной области. А как будет выглядеть твое приложение - это уже стадия проектирования на основании исследования.

Твой анализ = это не анализ. Ты на него потратил 30 секунд. Если бы ты анализировал, то описал бы свойства существующих приложений.

**Comment by greguar97** [comment]
Попытался исправить замечания: 
[ТЗ АНТОНОВ V2.docx](https://github.com/greguar97/greguar97/files/2637220/V2.docx)

**Comment by wldmr-key** [comment]
тз - приемлемо
описание предметной области - по-прежнему тебя тянет к приложению. Основная канва - описываешь существующие процессы, которые нуждаются в автоматизации; основных действующих лиц, информационные сущности, входы и выходы. И только после этого формулируешь требования к своей системе.
Аналоги по-прежнему описаны очень поверхностно и пренебрежительно

**Comment by greguar97** [comment]
Новая версия: [ТЗ АНТОНОВ V3.docx](https://github.com/greguar97/greguar97/files/2645970/V3.docx)

**Comment by wldmr-key** [comment]
сойдет пока. Это все исследование? Если да, то почитай методичку...
