### ISSUE TITLE
Концептуальная схема и Логическая схема

### ISSUE THREAD

**Issue by greguar97** [greguar97/greguar97#2]

**Comment by greguar97** [comment]
Концептуальная схема: ![default](https://user-images.githubusercontent.com/45518275/49332021-17af8800-f5b7-11e8-82eb-6ef75659f48d.jpg)

**Comment by wldmr-key** [comment]
концептуальная схема должна сопровождаться словами, из которых можно понять смысл, вкладываемый автором в компоненты схемы. Но уже сейчас очевидно, что домашние работы не оцениваются. Хорошая школа
