### ISSUE TITLE
РПЗ КР1

### ISSUE THREAD

**Issue by greguar97** [greguar97/greguar97#6]

**Comment by greguar97** [comment]
РПЗ КР 1 
[RpskirilovMY.docx](https://github.com/greguar97/greguar97/files/2687676/RpskirilovMY.docx)
 Что нужно исправить что бы получить тройку?

**Comment by wldmr-key** [comment]
Должна быть иллюзия, что приложение написано. Пока такой нет. Скриншоты заполненные, например...
и коды в репозитории

**Comment by greguar97** [comment]
код вроде залил на гитхаб или в курсовую его добавить? Вот с новыми скринами:
[RpskirilovMY2.docx](https://github.com/greguar97/greguar97/files/2692398/RpskirilovMY2.docx)
